[package]
name = "rene"
description = "Computational geometry."
license = "MIT"
license-file = "LICENSE"
version = "0.0.0"
edition = "2018"

[lib]
name = "rene"
crate-type = ["cdylib", "rlib"]

[dependencies]
rithm= "^7.1.0"

[dependencies.pyo3]
version = "^0.16.4"
features = ["extension-module"]

[dependencies.pyo3-ffi]
version = "^0.16.4"
features = ["extension-module"]

[build-dependencies]
pyo3-build-config = "^0.16.4"
