[package]
name = "rene"
description = "Computational geometry."
license = "MIT"
license-file = "LICENSE"
version = "0.1.0-alpha"
edition = "2018"
rust-version = "1.66.0"

[lib]
name = "rene"
crate-type = ["cdylib", "rlib"]

[dependencies]
rithm = "^10.3.0"

[dependencies.traiter]
version = "^0.1.0"
features = ["numbers"]

[dependencies.pyo3]
version = "^0.17.1"
features = ["extension-module"]

[dependencies.pyo3-ffi]
version = "^0.17.1"
features = ["extension-module"]

[build-dependencies]
pyo3-build-config = "^0.17.1"
