version: '3'

services:
  rene-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/rene-cpython:0.1.0
    volumes:
      - ./Cargo.toml:/opt/rene/Cargo.toml
      - ./pyproject.toml:/opt/rene/pyproject.toml
      - ./README.md:/opt/rene/README.md
      - ./rene:/opt/rene/rene
      - ./rust-toolchain.toml:/opt/rene/rust-toolchain.toml
      - ./setup.py:/opt/rene/setup.py
      - ./src:/opt/rene/src
      - ./tests:/opt/rene/tests
    entrypoint: pytest
